name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for Maven wrapper
        run: chmod +x lemonlot-backend/mvnw

      - name: Build and test backend
        run: |
          cd lemonlot-backend
          ./mvnw clean install

  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies and run tests
        run: |
          cd lemonlot-frontend
          npm install
          npm test

  codeql-analysis:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/setup-codeql@v2
        with:
          languages: java,javascript # Include both languages for analysis
      
      - name: Build the Backend
        run: |
          cd lemonlot-backend
          ./mvnw install # Build the Spring Boot app

      - name: Run CodeQL for Backend
        uses: github/codeql-action/analyze@v2
        with:
          category: '/language:java'
          upload: true

      - name: Build the Frontend
        run: |
          cd lemonlot-frontend
          npm install
          npm run build # Build the React app

      - name: Run CodeQL for Frontend
        uses: github/codeql-action/analyze@v2
        with:
          category: '/language:javascript'
          upload: true
